<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Box2d v3 for .NET</Title>
		<Authors>Thomas Vantroyen</Authors>
		<Description>A thin Box2D v3 .NET wrapper that stays true to the original API.</Description>
		<PackageProjectUrl>https://github.com/thomasvt/Box2D3Net</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/thomasvt/Box2D3Net</RepositoryUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn> <!-- suppress warnings for missing docs -->
		<Version>3.1.8.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="box2d.dll" Pack="true" PackagePath="runtimes/win-x64/native" CopyToOutputDirectory="PreserveNewest" />
		<None Include="box2dd.dll" Pack="true" PackagePath="runtimes/win-x64/native" CopyToOutputDirectory="PreserveNewest" />
		<None Include="libbox2d.so" Pack="true" PackagePath="runtimes/linux-x64/native" CopyToOutputDirectory="PreserveNewest" />
		<None Include="libbox2dd.so" Pack="true" PackagePath="runtimes/linux-x64/native" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
